config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contato.urls'))
]

contato/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.ContatoListView.as_view(), name='index'),
    path('create', views.ContatoCreateView.as_view(), name='create'),
    path('<int:pk>', views.ContatoDetailView.as_view(), name='detail')
]

contato/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Contato(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=180, blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.name} {self.last_name}"

    def get_absolute_url(self):
        return reverse('home:detail', kwargs={'pk': self.pk})

contato/forms.py
from django import forms
from .models import Contato

class ContatoForm(forms.ModelForm):

    class Meta:
        model = Contato
        fields = ['name', 'last_name', 'phone', 'email', 'description', 'category']

contato/views.py
from django.views import generic
from .models import Contato, Category
from .forms import ContatoForm
from django.urls import reverse_lazy
from django.db.models import Q, Value
from django.db.models.functions import Concat

# def gera():
#     data = ["Ad\u00e3o Uchoa", "Amadeu P\u00e1dua", "Am\u00e9rico Couto", "Angelino Alburquerque", "Anind Santiago",
#             "Ant\u00f3nia Soares", "Brites Puentes", "Catarina Silveira", "Claudemira Ventura", "Dinis Guaran\u00e1",
#             "Emanuel Raminhos", "Estanislau Vargas", "Eurico Parente", "Evaristo Passos", "Fabiana Belchiorinho",
#             "Filipe Trist\u00e3o", "Frederica Cayado", "Guterre Leit\u00e3o", "Helo\u00edsa Macedo",
#             "Herculano Gouveia", "H\u00e9lio Guedez", "Ilma Botica", "Israel Ignacio", "Janda\u00edra Palma",
#             "Juliano Telles", "Ju\u00e7ara Valent\u00edn", "Leopoldina Andrade", "Luciano Caldas",
#             "L\u00facia Vergueiro", "Margarida Nascimento", "Miru Brum", "M\u00e1ximo Trinidad", "Neusa Lemes",
#             "Nivaldo Mata", "Oliveira Briones", "Pandora Brum", "Pen\u00e9lope Cordero", "Roberto Alvarenga",
#             "Rodolfo Souza", "Rudi Paranhos", "Son\u00e1s Guedes", "Son\u00e1s Guzm\u00e1n",
#             "Suni\u00e1rio Rem\u00edgio", "Tabalipa Carmona", "Tairine Anhaia", "Tobias Fartaria",
#             "Ubirat\u00e3 Guar\u00e1", "Ulrico Ornellas", "Vanessa Murici", "V\u00e2nia Sarmiento"]
#
#     for d in data:
#         ddd = str(randint(1, 9)) + str(randint(0, 9))
#         digitos1 = str(randint(1, 9)) + str(randint(1, 9)) + str(randint(1, 9)) + str(randint(1, 9))
#         digitos2 = str(randint(1, 9)) + str(randint(1, 9)) + str(randint(1, 9)) + str(randint(1, 9))
#         telefone = f"({ddd}) {digitos1} - {digitos2}"
#         fullname = d.split(" ")
#         name = fullname[0]
#         lastname = fullname[1]
#         category = Category.objects.get(pk=randint(1, 5))
#         newcontato = Contato(name=name, last_name=lastname, phone=telefone, category=category)
#         newcontato.save()


class ContatoListView(generic.ListView):
    template_name = "contato/index.html"
    model = Contato
    context_object_name = 'contatos'
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        full_name = Concat('name', Value(' '), 'last_name')
        query = self.request.GET.get('query')
        if query:
            qs = qs.annotate(full_name=full_name)\
                .filter(Q(full_name__contains=query) | Q(phone__contains=query))
        else:
            qs = qs.order_by('-id')
        return qs


class ContatoDetailView(generic.DetailView):
    model = Contato
    template_name = "contato/detail.html"
    context_object_name = 'contato'


class ContatoCreateView(generic.CreateView):
    model = Contato
    template_name = "contato/create.html"
    form_class = ContatoForm
    success_url = reverse_lazy('home:index')

contato/templates/contato/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block 'title' %} Criar Novo Contato {% endblock %}


{% block 'content' %}

    <div class="container">
        <h3 class="text-center mt-5">Criar Novo Contato</h3>

        <form action="" method="post">
            {% csrf_token %}

                {{ form|crispy }}

            <button class="btn btn-primary">Salvar</button>
            <a href="{% url 'home:index' %}" class="btn btn-danger float-right">Voltar</a>
        </form>

    </div>




{% endblock %}

contato/templates/contato/detail.html
{% extends 'base.html' %}

{% block 'title' %} {{ contato.name }} {{ contato.last_name }} {% endblock %}

{% block 'content' %}

    <h4 class="text-center mt-5"> Detalhes do contato </h4>
    <div class="card mt-2">
        <div class="card-title text-center font-weight-bold">
            {{ contato.name }} {{ contato.last_name }}
        </div>

        <div class="card-body">

            <h6>Nome: {{ contato.name }}</h6>
            <h6>Sobrenome: {{ contato.last_name }}</h6>
            <h6>Telefone: {{ contato.phone }}</h6>
            <h6>Email: {{ contato.email }}</h6>
            <h6>Descrição: {{ contato.description }}</h6>
            <h6>Categoria: {{ contato.category }}</h6>

            <div class="mt-3">
                <a href="" class="btn btn-info">Editar</a>
                <a href="" class="btn btn-danger">Deletar</a>
            </div>
        </div>

    </div>

{% endblock %}

contato/templates/contato/index.html
{% extends 'base.html' %}

{% block 'title' %} Agenda - Lista {% endblock %}

{% block 'content' %}


    <h2 class="text-center mt-3">Lista de Contatos</h2>
    <a href="{% url 'home:create' %}" class="btn btn-primary my-3">Adicionar novo</a>
    <form action="" method="get">
        <div class="form-group">
            <label for="query">Pesquisar</label>
            <input type="text" name="query" id="query" class="form-control"
                   placeholder="nome, sobrenome ou telefone">
        </div>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Sobrenome</th>
                <th>Telefone</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
            {% for contato in contatos %}
                <tr>
                    <td><a href="{{ contato.get_absolute_url }}">{{ contato.name }}</a></td>
                    <td>{{ contato.last_name }}</td>
                    <td>{{ contato.phone }}</td>
                    <td>{{ contato.category }}</td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>

<nav aria-label="Page navigation">
      <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
          {% endif %}

        {% for page in page_obj.paginator.page_range %}
          {% if page_obj.number == page %}
            <li class="page-item active">
              <a class="page-link" href="/?page={{page}}">{{page}}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="/?page={{page}}&query={{request.GET.query}}">{{page}}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
      </ul>
    </nav>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <title>{% block 'title' %}Lista de Contatos{% endblock%}</title>
</head>
<body>
    <div class="container">
        {% block 'content' %} {% endblock %}

    </div>

    <script src="{% static 'bootstrap/css/bootstrap.js' %}"></script>
</body>
</html>